version: '3'
services:
  redis:
    image: redis:bookworm
    ports:
      - "6379:6379"
  onetimesecret:
    image: onetimesecret/onetimesecret:latest
    environment:
      REDIS_URL: redis://redis:6379/0
      COLONEL: admin@example.com
      HOST: localhost:3000
      SSL: "false"
      RACK_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - redis
